name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: zig-0.14.0-dev.3298+6fe1993d8
      - name: Test
        run: zig build test --summary all
